# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(711, 526))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tabInstructors = QtWidgets.QWidget()
        self.tabInstructors.setObjectName("tabInstructors")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabInstructors)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.tabInstructors)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnInstrAdd = QtWidgets.QPushButton(self.frame)
        self.btnInstrAdd.setObjectName("btnInstrAdd")
        self.horizontalLayout.addWidget(self.btnInstrAdd)
        self.btnInstrImport = QtWidgets.QPushButton(self.frame)
        self.btnInstrImport.setObjectName("btnInstrImport")
        self.horizontalLayout.addWidget(self.btnInstrImport)
        self.verticalLayout_2.addWidget(self.frame)
        self.treeInstr = QtWidgets.QTreeView(self.tabInstructors)
        self.treeInstr.setObjectName("treeInstr")
        self.verticalLayout_2.addWidget(self.treeInstr)
        self.tabWidget.addTab(self.tabInstructors, "")
        self.tabRooms = QtWidgets.QWidget()
        self.tabRooms.setObjectName("tabRooms")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabRooms)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.tabRooms)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnRoomAdd = QtWidgets.QPushButton(self.frame_2)
        self.btnRoomAdd.setObjectName("btnRoomAdd")
        self.horizontalLayout_2.addWidget(self.btnRoomAdd)
        self.btnRoomImport = QtWidgets.QPushButton(self.frame_2)
        self.btnRoomImport.setObjectName("btnRoomImport")
        self.horizontalLayout_2.addWidget(self.btnRoomImport)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.treeRoom = QtWidgets.QTreeView(self.tabRooms)
        self.treeRoom.setObjectName("treeRoom")
        self.verticalLayout_3.addWidget(self.treeRoom)
        self.tabWidget.addTab(self.tabRooms, "")
        self.tabSubjects = QtWidgets.QWidget()
        self.tabSubjects.setObjectName("tabSubjects")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabSubjects)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tabSubjects)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnSubjAdd = QtWidgets.QPushButton(self.frame_3)
        self.btnSubjAdd.setObjectName("btnSubjAdd")
        self.horizontalLayout_3.addWidget(self.btnSubjAdd)
        self.btnSubjImport = QtWidgets.QPushButton(self.frame_3)
        self.btnSubjImport.setObjectName("btnSubjImport")
        self.horizontalLayout_3.addWidget(self.btnSubjImport)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.treeSubj = QtWidgets.QTreeView(self.tabSubjects)
        self.treeSubj.setObjectName("treeSubj")
        self.verticalLayout_4.addWidget(self.treeSubj)
        self.tabWidget.addTab(self.tabSubjects, "")
        self.tabSections = QtWidgets.QWidget()
        self.tabSections.setObjectName("tabSections")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabSections)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.tabSections)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSecAdd = QtWidgets.QPushButton(self.frame_4)
        self.btnSecAdd.setObjectName("btnSecAdd")
        self.horizontalLayout_4.addWidget(self.btnSecAdd)
        self.btnSecImport = QtWidgets.QPushButton(self.frame_4)
        self.btnSecImport.setObjectName("btnSecImport")
        self.horizontalLayout_4.addWidget(self.btnSecImport)
        self.verticalLayout_5.addWidget(self.frame_4)
        self.treeSec = QtWidgets.QTreeView(self.tabSections)
        self.treeSec.setObjectName("treeSec")
        self.verticalLayout_5.addWidget(self.treeSec)
        self.tabWidget.addTab(self.tabSections, "")
        self.tabScenario = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabScenario.sizePolicy().hasHeightForWidth())
        self.tabScenario.setSizePolicy(sizePolicy)
        self.tabScenario.setObjectName("tabScenario")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabScenario)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.tabScenario)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnScenImport = QtWidgets.QPushButton(self.frame_5)
        self.btnScenImport.setObjectName("btnScenImport")
        self.horizontalLayout_5.addWidget(self.btnScenImport)
        self.btnScnExport = QtWidgets.QPushButton(self.frame_5)
        self.btnScnExport.setObjectName("btnScnExport")
        self.horizontalLayout_5.addWidget(self.btnScnExport)
        self.btnScenGenerate = QtWidgets.QPushButton(self.frame_5)
        self.btnScenGenerate.setObjectName("btnScenGenerate")
        self.horizontalLayout_5.addWidget(self.btnScenGenerate)
        self.btnScenResult = QtWidgets.QPushButton(self.frame_5)
        self.btnScenResult.setObjectName("btnScenResult")
        self.horizontalLayout_5.addWidget(self.btnScenResult)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.treeScen = QtWidgets.QTreeView(self.tabScenario)
        self.treeScen.setObjectName("treeScen")
        self.verticalLayout_6.addWidget(self.treeScen)
        self.tabWidget.addTab(self.tabScenario, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAdd_Instructor = QtWidgets.QAction(MainWindow)
        self.actionAdd_Instructor.setObjectName("actionAdd_Instructor")
        self.actionView_Instructors = QtWidgets.QAction(MainWindow)
        self.actionView_Instructors.setObjectName("actionView_Instructors")
        self.actionAdd_Room = QtWidgets.QAction(MainWindow)
        self.actionAdd_Room.setObjectName("actionAdd_Room")
        self.actionView_Rooms = QtWidgets.QAction(MainWindow)
        self.actionView_Rooms.setObjectName("actionView_Rooms")
        self.actionAdd_Subject = QtWidgets.QAction(MainWindow)
        self.actionAdd_Subject.setObjectName("actionAdd_Subject")
        self.actionView_Subjects = QtWidgets.QAction(MainWindow)
        self.actionView_Subjects.setObjectName("actionView_Subjects")
        self.actionAdd_Sections = QtWidgets.QAction(MainWindow)
        self.actionAdd_Sections.setObjectName("actionAdd_Sections")
        self.actionView_Sections = QtWidgets.QAction(MainWindow)
        self.actionView_Sections.setObjectName("actionView_Sections")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionView_Results = QtWidgets.QAction(MainWindow)
        self.actionView_Results.setObjectName("actionView_Results")
        self.actionGenerate = QtWidgets.QAction(MainWindow)
        self.actionGenerate.setObjectName("actionGenerate")
        self.actionImport_2 = QtWidgets.QAction(MainWindow)
        self.actionImport_2.setObjectName("actionImport_2")
        self.actionExport_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_2.setObjectName("actionExport_2")
        self.actionScenario_Summary = QtWidgets.QAction(MainWindow)
        self.actionScenario_Summary.setObjectName("actionScenario_Summary")
        self.actionGenerate_2 = QtWidgets.QAction(MainWindow)
        self.actionGenerate_2.setObjectName("actionGenerate_2")
        self.actionView_Results_2 = QtWidgets.QAction(MainWindow)
        self.actionView_Results_2.setObjectName("actionView_Results_2")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionInstructions)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GA Class Scheduler"))
        self.tabInstructors.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.btnInstrAdd.setText(_translate("MainWindow", "Add Instructor"))
        self.btnInstrImport.setText(_translate("MainWindow", "Import from CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabInstructors), _translate("MainWindow", "Instructors"))
        self.btnRoomAdd.setText(_translate("MainWindow", "Add Room"))
        self.btnRoomImport.setText(_translate("MainWindow", "Import from CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRooms), _translate("MainWindow", "Rooms"))
        self.btnSubjAdd.setText(_translate("MainWindow", "Add Subject"))
        self.btnSubjImport.setText(_translate("MainWindow", "Import from CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSubjects), _translate("MainWindow", "Subjects"))
        self.btnSecAdd.setText(_translate("MainWindow", "Add Section"))
        self.btnSecImport.setText(_translate("MainWindow", "Import from CSV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSections), _translate("MainWindow", "Sections"))
        self.btnScenImport.setText(_translate("MainWindow", "Import"))
        self.btnScnExport.setText(_translate("MainWindow", "Export"))
        self.btnScenGenerate.setText(_translate("MainWindow", "Generate"))
        self.btnScenResult.setText(_translate("MainWindow", "View Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabScenario), _translate("MainWindow", "Scenario Manager"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAdd_Instructor.setText(_translate("MainWindow", "Add Instructor"))
        self.actionView_Instructors.setText(_translate("MainWindow", "View Instructors"))
        self.actionAdd_Room.setText(_translate("MainWindow", "Add Room"))
        self.actionView_Rooms.setText(_translate("MainWindow", "View Rooms"))
        self.actionAdd_Subject.setText(_translate("MainWindow", "Add Subject"))
        self.actionView_Subjects.setText(_translate("MainWindow", "View Subjects"))
        self.actionAdd_Sections.setText(_translate("MainWindow", "Add Sections"))
        self.actionView_Sections.setText(_translate("MainWindow", "View Sections"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionView_Results.setText(_translate("MainWindow", "View Results"))
        self.actionGenerate.setText(_translate("MainWindow", "Generate"))
        self.actionImport_2.setText(_translate("MainWindow", "Import"))
        self.actionExport_2.setText(_translate("MainWindow", "Export"))
        self.actionScenario_Summary.setText(_translate("MainWindow", "Scenario Summary"))
        self.actionGenerate_2.setText(_translate("MainWindow", "Generate"))
        self.actionView_Results_2.setText(_translate("MainWindow", "View Results"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionAbout.setText(_translate("MainWindow", "About"))